#!/usr/bin/env php
<?php

declare(strict_types=1);

use Tempest\Console\ConsoleApplication;
use Tempest\Core\DiscoveryLocation;

try {
    require_once __DIR__ . '/vendor/autoload.php';
} catch (Throwable) {
    require_once getcwd() . '/../autoload.php';
}

ConsoleApplication::boot(
        name: 'Process hour slab',
        discoveryLocations: [
        new DiscoveryLocation('Config', 'config'),
    ])->run();

exit;
